name: Cypress Test

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install modules
        run: npm ci

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          record: true
          
        run: npx cypress run --record --key $CYPRESS_RECORD_KEY
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}