name: Cypress Test

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install modules
        run: npm ci

      - name: Verify Cypress Record Key
          run: echo "CYPRESS_RECORD_KEY=${CYPRESS_RECORD_KEY}"
          env:
            CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
      - name: List environment variables
        run: env
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}    

      - name: Run cypress test
        run: npx cypress run --record --key $CYPRESS_RECORD_KEY
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}